language: go
go:
  - "1.13"
  - "1.14"
  - "1.15"
  - tip
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - portaudio19-dev
      - libportmidi-dev
matrix:
  allow_failures:
    - go: tip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python && brew install portmidi portaudio; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CGO_LDFLAGS="-lportmidi -lporttime -L/usr/lib -L/usr/local/lib"; fi
  - go get -u golang.org/x/lint/golint

script:
  - make ci
