[[constraint]]
  name = "github.com/brettbuddin/musictheory"
  version = "0.0.11"

[[constraint]]
  branch = "master"
  name = "github.com/gordonklaus/portaudio"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/rakyll/portmidi"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  name = "github.com/c-bata/go-prompt"
  branch = "master"
