[[constraint]]
  name = "buddin.us/musictheory"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/gordonklaus/portaudio"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/rakyll/portmidi"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/c-bata/go-prompt"
  branch = "master"
